char_starting_location: [-0.5, -0.5, -0.5]
bvh_projection_bodypart_groups:
- bvh_joint_names:
  - LeftShoulder
  - LeftElbow
  - LeftWrist
  - LFingers
  - RightShoulder
  - RightElbow
  - RightWrist
  - RFingers
  method: pca
  name: Upper Limbs
- bvh_joint_names:
  - LeftHip
  - LeftKnee
  - LeftAnkle
  - LeftToe
  - RightHip
  - RightKnee
  - RightAnkle
  - RightToe
  method: pca
  name: Lower Limbs
- bvh_joint_names:
  - Hips
  - Chest
  - Chest2
  - Head
  method: pca
  name: Trunk
char_bodypart_groups:
- bvh_depth_drivers:
  - Hips
  char_joints:
  - right_hip_b
  - left_hip_b
  - right_hip_f
  - left_hip_f
  - hip
  - torso
  - neck
- bvh_depth_drivers:
  - RightAnkle
  char_joints:
  - left_knee_b
  - left_foot_b
- bvh_depth_drivers:
  - LeftAnkle
  char_joints:
  - right_knee_b
  - right_foot_b
- bvh_depth_drivers:
  - RightAnkle
  char_joints:
  - left_knee_f
  - left_foot_f
- bvh_depth_drivers:
  - LeftAnkle
  char_joints:
  - right_knee_f
  - right_foot_f
char_bvh_root_offset:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_joints:
  - - RightAnkle
    - RightKnee
    - RightHip
  - - LeftAnkle
    - LeftKnee
    - LeftHip
  char_joints:
  - - left_foot_f
    - left_knee_f
    - left_hip_f
  - - right_foot_f
    - right_knee_f
    - right_hip_f
  - - left_foot_b
    - left_knee_b
    - left_hip_b
  - - right_foot_b
    - right_knee_b
    - right_hip_b
char_joint_bvh_joints_mapping:
  left_knee_b: !!python/tuple
  - LeftShoulder
  - LeftElbow
  left_foot_f: !!python/tuple
  - LeftKnee
  - LeftAnkle
  left_foot_b: !!python/tuple
  - LeftElbow
  - LeftWrist
  left_knee_f: !!python/tuple
  - LeftHip
  - LeftKnee
  torso: !!python/tuple
  - Hips
  - Chest2
  neck: !!python/tuple
  - Hips
  - Head
  right_knee_b: !!python/tuple
  - RightShoulder
  - RightElbow
  right_foot_f: !!python/tuple
  - RightKnee
  - RightAnkle
  right_foot_b: !!python/tuple
  - RightElbow
  - RightWrist
  right_knee_f: !!python/tuple
  - RightHip
  - RightKnee
char_runtime_checks: []