char_starting_location: [-0.5, -0.5, -0.5]
bvh_projection_bodypart_groups:
- bvh_joint_names:
  - LeftShoulder
  - LeftArm
  - LeftForeArm
  - LeftHand
  - RightShoulder
  - RightArm
  - RightForeArm
  - RightHand
  method: pca
  name: Upper Limbs
- bvh_joint_names:
  - LeftUpLeg
  - LeftLeg
  - LeftFoot
  - RightUpLeg
  - RightLeg
  - RightFoot
  method: pca
  name: Lower Limbs
- bvh_joint_names:
  - Hips
  - Neck
  - Spine
  - Spine1
  method: frontal
  name: Trunk
char_bodypart_groups:
- bvh_depth_drivers:
  - Hips
  char_joints:
  - right_shoulder
  - left_shoulder
  - right_hip
  - left_hip
  - hip
  - torso
  - neck
- bvh_depth_drivers:
  - LeftHand
  char_joints:
  - left_elbow
  - left_hand
- bvh_depth_drivers:
  - RightHand
  char_joints:
  - right_elbow
  - right_hand
- bvh_depth_drivers:
  - LeftFoot
  char_joints:
  - left_knee
  - left_foot
- bvh_depth_drivers:
  - RightFoot
  char_joints:
  - right_knee
  - right_foot
char_bvh_root_offset:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_joints:
  - - RightUpLeg
    - RightLeg
    - RightFoot
  - - LeftUpLeg
    - LeftLeg
    - LeftFoot
  char_joints:
  - - left_foot
    - left_knee
    - left_hip
  - - right_foot
    - right_knee
    - right_hip
char_joint_bvh_joints_mapping:
  left_elbow: !!python/tuple
  - LeftArm
  - LeftForeArm
  left_foot: !!python/tuple
  - LeftLeg
  - LeftFoot
  left_hand: !!python/tuple
  - LeftForeArm
  - LeftHand
  left_knee: !!python/tuple
  - LeftUpLeg
  - LeftLeg
  torso: !!python/tuple
  - Spine
  - Spine1
  neck: !!python/tuple
  - Spine1
  - Neck
  right_elbow: !!python/tuple
  - RightArm
  - RightForeArm
  right_foot: !!python/tuple
  - RightLeg
  - RightFoot
  right_hand: !!python/tuple
  - RightForeArm
  - RightHand
  right_knee: !!python/tuple
  - RightUpLeg
  - RightLeg
char_runtime_checks: []