char_starting_location: [-0.5, -0.5, -0.5]
bvh_projection_bodypart_groups:
- bvh_joint_names:
  - LeftShoulder
  - LeftArm
  - LeftForeArm
  - LeftHand
  - RightShoulder
  - RightArm
  - RightForeArm
  - RightHand
  method: frontal
  name: Upper Limbs
- bvh_joint_names:
  - LeftHipJoint
  - LeftUpLeg
  - LeftLeg
  - LeftFoot
  - RightHipJoint
  - RightUpLeg
  - RightLeg
  - RightFoot
  method: frontal
  name: Lower Limbs
- bvh_joint_names:
  - Hips
  - Neck
  - Neck1
  - Spine
  - Spine1
  - LowerBack
  method: frontal
  name: Trunk
char_bodypart_groups:
- bvh_depth_drivers:
  - Hips
  char_joints:
  - right_hip_b
  - left_hip_b
  - right_hip_f
  - left_hip_f
  - hip
  - torso
  - neck
- bvh_depth_drivers:
  - LeftHand
  char_joints:
  - left_knee_b
  - left_foot_b
- bvh_depth_drivers:
  - RightHand
  char_joints:
  - right_knee_b
  - right_foot_b
- bvh_depth_drivers:
  - LeftFoot
  char_joints:
  - left_knee_f
  - left_foot_f
- bvh_depth_drivers:
  - RightFoot
  char_joints:
  - right_knee_f
  - right_foot_f
char_bvh_root_offset:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_joints:
  - - RightUpLeg
    - RightLeg
    - RightFoot
  - - LeftUpLeg
    - LeftLeg
    - LeftFoot
  char_joints:
  - - left_foot_f
    - left_knee_f
    - left_hip_f
  - - right_foot_f
    - right_knee_f
    - right_hip_f
  - - left_foot_b
    - left_knee_b
    - left_hip_b
  - - right_foot_b
    - right_knee_b
    - right_hip_b
char_joint_bvh_joints_mapping:
  left_knee_b: !!python/tuple
  - LeftArm
  - LeftForeArm
  left_foot_f: !!python/tuple
  - LeftLeg
  - LeftFoot
  left_foot_b: !!python/tuple
  - LeftForeArm
  - LeftHand
  left_knee_f: !!python/tuple
  - LeftUpLeg
  - LeftLeg
  torso: !!python/tuple
  - Spine
  - Spine1
  neck: !!python/tuple
  - Spine1
  - Neck
  right_knee_b: !!python/tuple
  - RightArm
  - RightForeArm
  right_foot_f: !!python/tuple
  - RightLeg
  - RightFoot
  right_foot_b: !!python/tuple
  - RightForeArm
  - RightHand
  right_knee_f: !!python/tuple
  - RightUpLeg
  - RightLeg
char_runtime_checks: []