filepath: examples/bvh/cmu1/jumping_jacks.bvh
start_frame_idx: 0
end_frame_idx: 125
groundplane_joint: lFoot
forward_perp_joint_vectors:
  - - rButtock
    - lButtock
  - - lShldr
    - rShldr
scale: 0.025
up: +y
