filepath: examples/bvh/fair1/zombie.bvh
start_frame_idx: 0
end_frame_idx: 500 # 779
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftArm
    - RightArm
scale: 0.025
up: -y
