scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/char7/char_cfg.yaml
      motion_cfg: examples/config/motion/zombie.yaml
      retarget_cfg: examples/config/retarget/four_legs.yaml
view:
  #BACKGROUND_IMAGE: examples/characters/char7/background.png
  WINDOW_DIMENSIONS: [320, 240]
  CAMERA_POS: [0.1, 0.1, 0.5]
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./video.gif